export const randomActsOfKindness = [
  "Pay for the coffee of the person in line behind you.",
  "Leave a kind note for a coworker or friend.",
  "Help an elderly person carry their groceries.",
  "Volunteer at a local charity or community organization.",
  "Send a care package to a soldier overseas.",
  "Offer to babysit for a busy parent.",
  "Plant a tree or flowers in a public space.",
  "Compliment a stranger on something you admire about them.",
  "Donate unused clothes or household items to a shelter.",
  "Write a thank-you note to someone who has made a difference in your life.",
  "Hold the door open for someone.",
  "Leave a generous tip for your server at a restaurant.",
  "Send a surprise gift to a friend or family member.",
  "Help a neighbor with their yard work or household chores.",
  "Donate blood to a local blood bank.",
  "Leave quarters at a laundromat for someone to find.",
  "Offer to walk a friend's dog or pet-sit for them.",
  "Send a handwritten letter to a loved one.",
  "Bring treats or snacks to share with your coworkers.",
  "Leave a positive review for a local business you enjoy.",
  "Offer to give a friend or family member a ride to an appointment.",
  "Buy a meal for a homeless person in your community.",
  "Volunteer at an animal shelter or rescue organization.",
  "Share your umbrella with someone on a rainy day.",
  "Donate books to a library or school.",
  "Leave uplifting or inspirational sticky notes in public places.",
  "Offer to help a student with their homework or studies.",
  "Give someone a genuine compliment.",
  "Sponsor a child through a reputable organization.",
  "Donate to a food bank or soup kitchen.",
  "Send flowers or a small gift to a nursing home resident.",
  "Offer to mentor a young person in your field of expertise.",
  "Organize a fundraiser for a cause you care about.",
  "Donate school supplies to a local school or classroom.",
  "Offer to pick up groceries for an elderly or disabled person.",
  "Leave a generous tip for a hardworking delivery person.",
  "Donate toys or games to a children's hospital.",
  "Offer to help someone move or organize their belongings.",
  "Give up your seat on public transportation for someone in need.",
  "Donate your hair to an organization that makes wigs for cancer patients.",
  "Send a care package to a college student or someone far from home.",
  "Spend quality time with a friend or family member who needs support.",
  "Leave encouraging notes in library books or public restrooms.",
  "Organize a community clean-up day in your neighborhood.",
  "Donate pet supplies to an animal shelter.",
  "Offer to tutor a student struggling in a particular subject.",
  "Help a stranger change a flat tire or jump-start their car.",
  "Buy a meal for a person experiencing homelessness.",
  "Donate to a charity that supports a cause you believe in.",
  "Offer to do household chores for a busy or elderly neighbor.",
  "Bake cookies or treats and share them with your neighbors.",
  "Give someone a hug or a sincere handshake.",
  "Leave a kind and encouraging comment on someone's social media post.",
  "Donate art supplies to a school or community center.",
  "Offer to help a friend or neighbor with home repairs or renovations.",
  "Support a local business by promoting them on social media.",
  "Write positive messages with sidewalk chalk in your neighborhood.",
  "Donate hygiene products to a homeless shelter.",
];
